#!/bin/sh
#
# $Id: run_chicago_regional_indepdent_eclipse_model.sh 726 2011-09-21 01:37:47Z astivala $
#

# .dzn file is generated by flowoutput_to_independent_schedule_dzn.py
DZN_FILE=chicago_regional_indepedent_schedule.dzn

# convert: Budget = [1000000.0, 4000000.0, 1500000.0, 3000000.0, 5000000.0];
# to:      budgets:  1000 4000 1500 3000 5000
budgets=`grep 'Budget =' $DZN_FILE | tr -d '[],;' | cut -d= -f2`

echo -n "budgets: "
for budget in $budgets
do
    budget000=`echo "$budget / 1000" | bc`
    printf "%d " $budget000
done
echo

mzn2fzn --output-to-stdout upgrade_schedule_independent.mzn $DZN_FILE | eclipse -e "flatzinc:fzn_run(fzn_ic)" | ../scripts/convert_eclipse_output_schedule_to_id_schedule.py -c $DZN_FILE

