#!/bin/sh
#
# summarize.sh - read VHT from tap_frankwolfe_mpi stderr and compare
#                pairwise change VHT with sum of individual change VHT
#
# $Id: summarize.sh 384 2011-06-21 01:13:47Z astivala $
#

NOCHANGES_VHT_FILE=results/ChicagoRegional_fw_out.txt
INDIVIDUAL_TAP_STDERR_FILE=results/ChicagoRegional_mods_goliath.err
PAIRWISE_TAP_STDERR_FILE=results/ChicagoRegional_pairwise.err
#PAIRWISE_TAP_STDERR_FILE=ChicagoRegional_mods_pairwise_warmstart_carlton.err

echo "# Generated by: $0"
echo "# On: " `date`
echo "# Machine: " `hostname`
echo "# Dirctory: " `pwd`
echo "# NOCHANGES_VHT_FILE = $NOCHANGES_VHT_FILE"
echo "# INDIVIDUAL_TAP_STDERR_FILE = $INDIVIDUAL_TAP_STDERR_FILE"
echo "# PAIRWISE_TAP_STDERR_FILE = $PAIRWISE_TAP_STDERR_FILE"

printf "ChangeId1\tChangeId2\tPairDeltaVHT\tSumDeltaVHT\tRelDiff\n"
orig_vht=`grep '^total cost' ${NOCHANGES_VHT_FILE} | awk '{print $4}'`
for pairid  in `grep VHT ${PAIRWISE_TAP_STDERR_FILE} | awk '{print $3}'`
do 
  id1=`echo $pairid | sed 's/\(.*\)_and_\(.*\)/\1/'`
  id2=` echo $pairid | sed 's/\(.*\)_and_\(.*\)/\2/'`
  pair_vht=`grep VHT ${PAIRWISE_TAP_STDERR_FILE} | grep ${pairid} | awk '{print $6}'`
  id1_vht=`grep VHT ${INDIVIDUAL_TAP_STDERR_FILE} | grep ${id1} | awk '{print $6}'`
  id2_vht=`grep VHT ${INDIVIDUAL_TAP_STDERR_FILE}  | grep ${id2} | awk '{print $6}'`
  pair_delta=`echo "$orig_vht - $pair_vht" | bc -l`
  id1_delta=`echo "$orig_vht - $id1_vht" | bc -l`
  id2_delta=`echo "$orig_vht - $id2_vht" | bc -l`
  sum_delta=`echo "$id1_delta + $id2_delta" | bc -l`
  abs_error=`echo "$sum_delta - $pair_delta" | bc -l`
  reldiff=`echo "$abs_error / $pair_delta" | bc -l`
  perc_error=`echo "100 * $abs_error / $pair_delta" | bc -l`
  printf '%s\t%s\t%10.0f\t%10.0f\t% f\n' $id1 $id2 $pair_delta $sum_delta $reldiff
done  | sort -k3,3nr
