#!/bin/sh
#
# summarize.sh - read VHT from tap_frankwolfe_mpi stderr and compare
#                pairwise change VHT with sum of individual change VHT
#
# $Id: summarize.sh 575 2011-08-18 01:33:21Z astivala $
#

if [ $# -ne 3 ]; then
  echo "Usage: $0 nocahnge_vht_file invidiual_tap_err_file pariwise_tap_err_file" >&2
  exit 1
fi

NOCHANGES_VHT_FILE=$1
INDIVIDUAL_TAP_STDERR_FILE=$2
PAIRWISE_TAP_STDERR_FILE=$3

echo "# Generated by: $0"
echo "# On: " `date`
echo "# Machine: " `hostname`
echo "# Dirctory: " `pwd`
echo "# NOCHANGES_VHT_FILE = $NOCHANGES_VHT_FILE"
echo "# INDIVIDUAL_TAP_STDERR_FILE = $INDIVIDUAL_TAP_STDERR_FILE"
echo "# PAIRWISE_TAP_STDERR_FILE = $PAIRWISE_TAP_STDERR_FILE"

printf "ChangeId1\tChangeId2\tPairDeltaVHT\tSumDeltaVHT\tRelDiff\n"
orig_vht=`grep 'total cost' ${NOCHANGES_VHT_FILE} | tail -n1 | awk '{print $NF}'`
for pairid  in `grep VHT ${PAIRWISE_TAP_STDERR_FILE} | awk '{print $3}'`
do 
  id1=`echo $pairid | sed 's/\(.*\)_and_\(.*\)/\1/'`
  id2=` echo $pairid | sed 's/\(.*\)_and_\(.*\)/\2/'`
  pair_vht=`grep VHT ${PAIRWISE_TAP_STDERR_FILE} | grep -w ${pairid} | awk '{print $6}'`
  id1_vht=`grep VHT ${INDIVIDUAL_TAP_STDERR_FILE} | grep -w ${id1} | awk '{print $6}'`
  id2_vht=`grep VHT ${INDIVIDUAL_TAP_STDERR_FILE}  | grep -w ${id2} | awk '{print $6}'`
  pair_delta=`echo "$orig_vht - $pair_vht" | bc -l`
  id1_delta=`echo "$orig_vht - $id1_vht" | bc -l`
  id2_delta=`echo "$orig_vht - $id2_vht" | bc -l`
  sum_delta=`echo "$id1_delta + $id2_delta" | bc -l`
  abs_error=`echo "$sum_delta - $pair_delta" | bc -l`
  reldiff=`echo "$abs_error / $pair_delta" | bc -l`
  perc_error=`echo "100 * $abs_error / $pair_delta" | bc -l`
  printf '%s\t%s\t%10.0f\t%10.0f\t% f\n' $id1 $id2 $pair_delta $sum_delta $reldiff
done  | sort -k3,3nr
